name: scanning-squid-analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - h5py
  - ipykernel=4.10.0
  - jupyter
  - jupyter_console
  - matplotlib
  - pint
  - pip
  - pyqtgraph
  - python=3.6
  - qcodes=0.1.1
  - qtpy
  - scipy
