name: scanning-squid-analysis
channels:
  - anaconda
  - conda-forge
  - defaults
dependencies:
  - h5py
  - ipykernel
  - ipython
  - jupyter
  - jupyter_console
  - matplotlib
  - pint
  - pip
  - pyqtgraph
  - qtpy
  - scipy
  - pip:
    - qcodes
