name: scanning-squid-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - h5py
  - ipykernel=4.10.0
  - ipython=7.2.0
  - jupyter
  - jupyter_console
  - matplotlib
  - pint
  - pyqtgraph
  - python=3.6
  - qcodes=0.1.1
  - qtpy
  - scipy
